Add pip upgrade command
After installing Jetpack on Jetson nano immediately, I ran docker_setup.sh, and the following error occurred
ModuleNotFoundError: No module named 'setuptools_rust'
The default pip is version 9, which is resolved after upgrading the pip module